config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :users
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews, only: [:create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :products
	has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
	def ensure_logged_in 
		unless current_user
			flash[:alert] = "Please log in"
			redirect_to new_session_path
    end
	end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :ensure_logged_in, only: [:new, :create, :edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to product_path(@product)
		else
			render :new
		end
	end

	def show
		@product = Product.find(params[:id])
		@review = Review.new
		@reviews = Review.where(product_id: @product.id)
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to root_path
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		Product.update(product_params)
		redirect_to product(params[:id])
	end

	private

	def product_params
		params.require(:product).permit(:name,:description,:price, :user_id)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def create
		@review = Review.create(review_params)
		redirect_to product_path(params[:review][:product_id])
	end

private

	def review_params
		params.require(:review).permit(:product_id, :review, :user_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: 'Successfully signed in'
		else
			flash[:alert] = 'Log in credentials incorrect'
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save 
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Successfully logged in!" #flash[:notice]
		else
			flash[:alert] = "There has been an error"
			render :new
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
	<%= link_to("Rainforest", root_url) %>
	<% if current_user %>
 		<%= link_to("Sign out", session_path(current_user) , method: 'delete') %>
 		<%= link_to("New product", new_product_path) %>
 	<% else %>
 		<%= link_to "Sign in", new_session_path %>
 		<%= link_to "Sign up", new_user_path %>
 	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header'  %>

	<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<%= form_for @product, method: 'post', do |f| %>

<%= f.text_field :name, placeholder: 'name' %>
<%= f.text_area :description, placeholder: 'description' %>
<%= f.submit "Post", '/product' %>

<% end %>

app/views/products/index.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>

<% @products.each do |product| %>
	<p><%= link_to product.name, product_path(product.id) %></p>
<% end %>

app/views/products/new.html.erb
<%= form_for @product do |f| %>

<%= f.text_field :name, placeholder: 'name' %>
<%= f.text_area :description, placeholder: 'description' %>
<% f.hidden_field :user_id, value: current_user.id %>
<%= f.submit "Post"  %>

<% end %>

app/views/products/show.html.erb
<% if @product.user_id == current_user.id %>	
	<% link_to 'edit', edit_product_path(@product) %>
	<% link_to 'delete', "/products/#{@product.id}", method: delete %>
<% end %>

	<h2><%= @product.name %></h2>
	<p><%= @product.description %></p>

	<div><%= form_for @review do |f| %>
		
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.hidden_field :product_id, value: @product.id %>
		<%= f.text_field :review, placeholder: 'comment' %>
		<%= f.submit 'post' %>

	<% end %>
	</div>

	<% @reviews.each do |review| %>

		<p><%= User.find(review.user_id).email %><%= review.review %></p>

	<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

	<%= f.text_field :email, placeholder: 'email' %>
	<%= f.password_field :password, placeholder: 'password' %>
	<%= f.password_field :password_confirmation, placeholder: 'confirm password' %>
	<%= f.submit "Sign up" %>

<% end %>